/**
 * Loads the committed test dataset into the active registries, for Node scripts.
 *
 * This is the suite's own data, generated by `npm run testdata`. It is not
 * product data and never ships in the app bundle — the ids below are neutral on
 * purpose, so a smoke failure reads as "the query layer broke", never as "the
 * demo numbers moved".
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createDb, setDb, type CatchflyDb } from '@catchfly/core/db.ts';
import type { CatchflyDataset } from '@catchfly/core/types.ts';

const here = dirname(fileURLToPath(import.meta.url));

export const TESTDATA_PATH = resolve(here, 'testdata/tiny.json');
export const CHROME_REPORT_PATH = resolve(here, 'testdata/chrome-report.json');

/** The ids the suite asserts against. The generator imports these too. */
export const TEST_PROJECT_ID = 'test-project';
export const TEST_RUN_BASELINE = 'run-a';
export const TEST_RUN_CANDIDATE = 'run-b';
export const TEST_RUN_FIXED = 'run-c';
export const TEST_RUN_OTHER_MODEL = 'run-d';

export function loadTestDb(): CatchflyDb {
  try {
    const dataset = JSON.parse(readFileSync(TESTDATA_PATH, 'utf8')) as CatchflyDataset;
    return setDb(createDb(dataset));
  } catch (error) {
    throw new Error(
      `Could not read ${TESTDATA_PATH} — run \`npm run testdata\` to generate it.\n${String(error)}`,
    );
  }
}
